'use strict';var qaa={TAB:0,Pj:1,un:2},mz=function(a){Cb("MediaRouter.CastStreaming.Start.Success",a,qaa)};var nz=hb("mr.mirror.cast.LogUploader"),pz=function(a,c,b){oz("raw_events.log.gz",a,c,b);return c?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+c+"'"):""},oz=function(a,c,b,d){if(0==c.size)nz.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,c);b&&e.append("comments",b);fx("https://clients2.google.com/cr/report",function(f){f=f.target;
var g=null;px(f)?(g=qx(f),nz.info("Upload to Crash succeeded: "+g)):nz.info("Upload to Crash failed. HTTP status: "+f.Ua());d&&d(g)},"POST",e,void 0,3E4)}};var qz=function(){this.b=0;Yl(this)},sz=function(){rz||(rz=new qz);return rz},raa=function(){var a=sz(),c={fraction:.01,autoSubmitTimeLimitMillis:6048E5},b=c.autoSubmitTimeLimitMillis,d=Date.now();return a.b&&b&&d-a.b<b?!1:Math.random()<c.fraction};qz.prototype.Fa=function(){return"mirror.cast.LogUtils"};qz.prototype.jb=function(){return[void 0,{lastAutoSubmitMillis:this.b}]};qz.prototype.ib=function(){var a=Wl(this);this.b=a&&a.lastAutoSubmitMillis||0};var rz=null;hb("mr.mirror.cast.LogUtils");var tz={zw:"OFFER",xs:"ANSWER",bx:"PRESENTATION",nu:"GET_STATUS",my:"STATUS_RESPONSE",mu:"GET_CAPABILITIES",Ts:"CAPABILITIES_RESPONSE",Nx:"RPC"};var saa=function(){this.capabilities=this.status=this.b=this.error=this.rpc=this.result=this.type=this.f=this.sessionId=null},uaa=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var c;uz(JSON.parse(a),function(d){c=taa(d)},function(){throw Error("non-Object result from JSON parse");});return c}catch(d){var b=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(b+". Input was "+a);},taa=function(a){var c=new saa;null!=a.sessionId&&(c.sessionId=String(a.sessionId));vz(a.seqNum,function(f){c.f=f},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var b=String(a.type).toUpperCase(),d=l(Object.keys(tz)),e=d.next();!e.done;e=d.next())if(tz[e.value]==b){c.type=b;break}if(!c.type)throw Error('not a known message "type"');
}"result"in a&&(c.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');c.rpc=new Uint8Array([].concat(n(atob(a.rpc))).map(function(f){return f.charCodeAt(0)}))}uz(a.error,function(f){c.error=vaa(f)},function(){throw Error('"error" must be an Object');});uz(a.answer,function(f){c.b=waa(f)},function(){throw Error('"answer" must be an Object');});uz(a.status,function(f){c.status=xaa(f)},function(){throw Error('"status" must be an Object');
});uz(a.capabilities,function(f){c.capabilities=yaa(f)},function(){throw Error('"capabilities" must be an Object');});return c},uz=function(a,c,b){void 0!==a&&(a instanceof Object?c(a):b())},vz=function(a,c,b){void 0!==a&&("number"!==typeof a?b():c(a))},wz=function(a,c,b){void 0!==a&&(a instanceof Array&&a.every(function(d){return"number"===typeof d})?c(a):b())},xz=function(a,c,b){void 0!==a&&(a instanceof Array?c(a.map(function(d){return String(d)})):b())},zaa=function(){this.j=null;this.b=[];this.f=
[];this.g=this.h=this.w=null},waa=function(a){var c=new zaa;vz(a.udpPort,function(b){c.j=b},function(){throw Error('"answer.udpPort" must be a number');});wz(a.sendIndexes,function(b){c.b=b},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});wz(a.ssrcs,function(b){c.f=b},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(c.w=String(a.IV));"receiverGetStatus"in a&&(c.h="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(c.g=
String(a.castMode));return c},Aaa=function(){this.details=this.description=this.code=null},vaa=function(a){var c=new Aaa;vz(a.code,function(b){c.code=b},function(){throw Error('"error.code" must be a number');});"description"in a&&(c.description=String(a.description));uz(a.details,function(b){c.details=b},function(){throw Error('"error.details" must be an Object');});return c},Baa=function(){this.f=this.b=null},xaa=function(a){var c=new Baa;vz(a.wifiSnr,function(b){c.b=b},function(){throw Error('"status.wifiSnr" must be a number');
});wz(a.wifiSpeed,function(b){c.f=b},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return c},Caa=function(){this.f=this.b=null},yaa=function(a){var c=new Caa;xz(a.mediaCaps,function(b){c.b=b},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');c.f=a.map(function(b){var d;uz(b,function(e){d=Daa(e)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return d})}return c},Eaa=function(){this.g=this.m=this.w=this.j=this.u=this.b=this.o=this.f=this.initDataTypes=this.h=null},Daa=function(a){var c=new Eaa;"keySystemName"in a&&(c.h=String(a.keySystemName));xz(a.initDataTypes,function(b){c.initDataTypes=b},function(){throw Error('"capabilities.initDataTypes" must be an array');});xz(a.codecs,function(b){c.f=b},function(){throw Error('"capabilities.codecs" must be an array');});xz(a.secureCodecs,function(b){c.o=b},function(){throw Error('"capabilities.secureCodecs" must be an array');
});xz(a.audioRobustness,function(b){c.b=b},function(){throw Error('"capabilities.audioRobustness" must be an array');});xz(a.videoRobustness,function(b){c.u=b},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(c.j=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(c.w=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(c.m=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(c.g=String(a.distinctiveIdentifierSupport));return c};var yz=function(a){this.l=hb("mr.mirror.cast.MessageDispatcher");this.h=a;this.b=null;this.f=new Map;this.g=0};yz.prototype.subscribe=function(a,c){if(this.f.has(a))throw Error("Attempt to multiple-subscribe to the same response type: "+a);this.f.set(a,c);this.g=0;ob(this.l,"Added subscriber for "+a+"-type messages.");this.b||(this.b=Ay(this.h),this.b.onMessage=this.j.bind(this))};
var zz=function(a,c){a.f.delete(c)&&ob(a.l,function(){return"Removed subscriber of "+c+"-type messages."});0==a.f.size&&a.b&&(a.b.Ya(),a.b=null)};yz.prototype.sendMessage=function(a){return this.b?"RPC"==a.type?this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Az=function(a,c,b,d,e){var f=null,g=function(){zz(a,b);null!=f&&(clearTimeout(f),f=null)};try{a.subscribe(b,function(k){e(k)&&g()})}catch(k){e(null,k);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(c).catch(function(k){g();e(null,k)})};
yz.prototype.j=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var c=void 0;try{c=uaa(a.data)}catch(d){c=d.message;break}if(c.type){var b=this.f.get(c.type);if(b)try{b(c);return}catch(d){c="Error thrown during delivery. Response was: "+(JSON.stringify(c)+". Error from subscriber callback ")+("was: "+d.message+".")}else c="Message was ignored: "+JSON.stringify(c)}else c="Message did not include response type: "+JSON.stringify(c)}while(0);
10>this.g?this.l.G(c):ob(this.l,c);++this.g}};var Bz=function(){this.b=Promise.resolve(1)},Dz=function(a,c,b){return Cz(a,function(d){return d==c},b)},Faa=function(a,c){var b=[3,4];return Cz(a,function(d){return-1!=b.indexOf(d)},c)},Ez=function(a,c){a.b=a.b.catch(function(){return 1});return Cz(a,function(){return!0},c)},Cz=function(a,c,b){var d,e,f=new Promise(function(g,k){d=g;e=k});a.b=a.b.then(function(g){if(!c(g))return e(Error("Operation requires a different starting checkpoint than "+g)),Promise.resolve(g);var k=new Gaa(g);try{var m=b(k)}catch(p){m=
Promise.reject(p)}return m.then(function(p){return d(p)},function(p){return e(p)}).then(function(){if(null===k.b)throw Error("A prior operation that started at "+(g+" did not complete."));return k.b})},function(g){e(g);throw g;});return f},Gaa=function(a){this.f=a;this.b=null},Fz=function(a,c){a.b="number"===typeof c?c:a.f};var Gz=chrome.cast.streaming,Iz=function(a,c,b,d,e){this.J=a.sessionId;this.u=a.Nf;this.R=a.Zd;this.g=c;this.H=b;this.N=d;this.T=Hz(e,"onAnswer",this.u);this.V=Hz(e,"onSessionStop",this.u);this.l=hb("mr.mirror.cast.StreamingLaunchWorkflow");this.D=new Bz;this.m=this.C=this.o=this.f=this.b=this.w=this.j=this.h=null};
Iz.prototype.start=function(a,c,b){var d=this;if(!a&&!c)return Promise.reject(Error("No tracks to stream"));var e=a instanceof Jz,f=c instanceof Jz;(e&&c&&!f||f&&a&&!e)&&Hb("Mixing remoting and non-remoting tracks");return Dz(this.D,1,function(g){d.h=a;d.j=c;d.w=b;d.l.info(function(){return"Launching streaming for "+Lz(d)+" "+("to a "+d.R+".")});return Haa(d).then(d.F.bind(d)).then(function(k){return Iaa(d,k).then(function(m){d.T();var p=Jaa(d,m,k);d.b=Mz(d,d.b,p);d.f=Mz(d,d.f,p);if(!d.b&&!d.f)throw Error("Receiver did not select any offers from: "+
JSON.stringify(k));d.C=!!m.h;d.m=function(v,A){v==d.b?d.w.Pe("Audio stream (id="+v+") error: "+A):v==d.f&&d.w.Pe("Video stream (id="+v+") error: "+A)};Gz.rtpStream.onError.addListener(d.m);return Kaa(d,m,p)})}).then(function(){d.l.info(function(){return"Launched streaming for "+Lz(d)});d.w.jg(d);Fz(g,2);return{Jo:d.b,es:d.f}})})};
Iz.prototype.stop=function(){var a=this;return Ez(this.D,function(c){if(!a.h&&!a.j)return Fz(c,1),Promise.resolve();a.l.info(function(){return"Stopping streaming for "+Lz(a)+"."});a.m&&(Gz.rtpStream.onError.removeListener(a.m),a.m=null);if(a.w){var b=a.w.Tg();a.w=null}else b=Promise.resolve();return b.then(function(){a.b&&(Gz.rtpStream.stop(a.b),Gz.rtpStream.destroy(a.b),a.b=null);a.f&&(Gz.rtpStream.stop(a.f),Gz.rtpStream.destroy(a.f),a.f=null);a.o&&(Gz.udpTransport.destroy(a.o),a.o=null);a.V();a.l.info(function(){return"Stopped streaming for "+
Lz(a)+"."});a.h=null;a.j=null;Fz(c,1)})})};
var Laa=function(a,c){var b=JSON.stringify(c);return Promise.all([a.b&&new Promise(function(d){return Gz.rtpStream.getRawEvents(a.b,b,d)}),a.f&&new Promise(function(d){return Gz.rtpStream.getRawEvents(a.f,b,d)})]).catch(function(d){a.l.error("Unexpected error when calling getRawEvents()",d);return[]}).then(function(d){return new Blob(d.filter(function(e){return!!e}),{type:"application/gzip"})})},Maa=function(a){return Promise.all([a.b&&new Promise(function(c){return Gz.rtpStream.getStats(a.b,c)}),
a.f&&new Promise(function(c){return Gz.rtpStream.getStats(a.f,c)})]).catch(function(c){a.l.error("Unexpected error when calling getStats()",c);return[]}).then(function(c){return Object.assign.apply(Object,[{}].concat(n(c.filter(function(b){return!!b}))))})},Lz=function(a){if(a.h&&a.j)var c="audio+video ";else if(a.h)c="audio-only ";else if(a.j)c="video-only ";else return"stopped";return a.h instanceof Jz||a.j instanceof Jz?c+"remoting":c+"streaming"},Haa=function(a){return new Promise(function(c){var b=
function(d,e,f){d&&!a.h&&(Gz.rtpStream.destroy(d),d=null);e&&!a.j&&(Gz.rtpStream.destroy(e),e=null);a.l.info(function(){return"Created Cast Streaming session: audioStreamId="+d+", videoStreamId="+e+"."});a.b=d;a.f=e;a.o=f;c()};a.h instanceof Jz||a.j instanceof Jz?Gz.session.create(null,null,b):Gz.session.create(a.h,a.j,b)})};
Iz.prototype.F=function(){for(var a=Lj(),c=Lj(),b=[],d=l([this.b,this.f]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.b,g=f?127:96,k=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,m=f?48E3:9E4,p=l(Gz.rtpStream.getSupportedParams(e)),v=p.next();!v.done;v=p.next())v=v.value,v.payload.payloadType=g,v.payload.maxLatency=this.g.maxLatencyMillis,v.payload.minLatency=this.g.minLatencyMillis,v.payload.animatedLatency=this.g.animatedLatencyMillis,v.payload.ssrc=
k,v.payload.clockRate=m,v.payload.aesKey=a,v.payload.aesIvMask=c,f?(v.payload.channels=2,v.payload.maxBitrate=this.g.audioBitrate,v.payload.maxFrameRate=100):(v.payload.minBitrate=this.g.minVideoBitrate,v.payload.maxBitrate=this.g.maxVideoBitrate,v.payload.maxFrameRate=this.g.maxFrameRate),b.push(new Naa(e,v));return b};
var Mz=function(a,c,b){c&&!b.some(function(d){return d.Qf==c})&&(a.l.G("Destroying RTP stream not selected by the receiver: id="+c),Gz.rtpStream.destroy(c),c=null);return c},Iaa=function(a,c){return new Promise(function(b,d){for(var e=[],f=0;f<c.length;++f){var g=c[f].params,k={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.g.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.g.dscpEnabled&&(k.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(k,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(k,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.g.maxWidth,height:a.g.maxHeight}]});e.push(k)}var m=a.h instanceof Jz||a.j instanceof Jz?"remoting":"mirroring",p={type:"OFFER",sessionId:a.J,seqNum:mn(a.H),offer:{castMode:m,receiverGetStatus:!0,supportedStreams:e}};a.l.info(function(){return"Sending OFFER message: "+JSON.stringify(p)});Az(a.N,p,"ANSWER",1E4,function(v,A){if(null==v)d(A);else if("ok"==v.result&&v.b){if(v.f!=p.seqNum)return a.l.G("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(v)),!1;((A=v.b.g)&&A!=m||!A&&"mirroring"!=m)&&a.l.error("Expected receiver to ANSWER with castMode="+m+", but got: "+A);ob(a.l,function(){return"Received ANSWER: "+JSON.stringify(v)});b(v.b)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(v)));return!0})})},Jaa=function(a,c,b){if(c.b.length!=c.f.length)return a.l.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(c)),[];for(var d=[],e={},f=0;f<c.b.length;e={We:e.We},++f){var g=c.b[f];if(0>g||g>=b.length)return a.l.error("Receiver selected invalid index ("+
g+" < "+b.length+") in ANSWER: "+JSON.stringify(c)),[];e.We=b[g];if(d.some(function(k){return function(m){return m.Qf==k.We.Qf}}(e)))return a.l.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(c)),[];e.We.params.payload.feedbackSsrc=c.f[g];if(d.some(function(k){return function(m){return m.params.payload.feedbackSsrc==k.We.params.payload.feedbackSsrc}}(e)))return a.l.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(c)),[];d.push(e.We)}return d},
Kaa=function(a,c,b){var d=null,e=function(){d&&(Gz.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(f,g){var k=c.j||2344;a.l.info(function(){return"Starting RTP streams to receiver at "+(a.u+":"+k)+(" for selected offers: "+JSON.stringify(b))});var m=a.o||-1;a.g.dscpEnabled&&(a.l.info("Enabled DSCP in sender."),Gz.udpTransport.setOptions(m,{DSCP:!0}));Gz.udpTransport.setDestination(m,{address:a.u,port:k});var p=new Set(b.map(function(A){return A.Qf}));d=function(A){p.delete(A);
0==p.size&&f()};Gz.rtpStream.onStarted.addListener(d);m=l(b);for(var v=m.next();!v.done;v=m.next())v=v.value,Gz.rtpStream.toggleLogging(v.Qf,a.g.enableLogging),Gz.rtpStream.start(v.Qf,v.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(f){e();throw f;})},Hz=function(a,c,b){var d=this;return a&&c in a?function(){try{a[c](b)}catch(e){d.l.error("Error from testHooks."+c,e)}}:function(){}},Naa=function(a,c){this.Qf=a;this.params=c},Jz=function(){};var Nz=function(a,c,b,d,e,f){this.m=a;this.N=Oaa(c,this.m.nb);this.H=new Iz(this.m.nb,b,d,e,f);this.C=e;this.j=new Bz;this.g=new Paa;this.D=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.l=hb("mr.mirror.cast.MediaRemoter");this.u=this.b=this.w=this.h=this.F=null;this.f=!0;this.o=this.J.bind(this)};
Nz.prototype.initialize=function(a,c){var b=this;return Dz(this.j,1,function(d){b.F=a;b.h=c;var e=b.D.createInterfacePtrAndBind();b.D.setConnectionErrorHandler(function(){b.l.info("Remoter mojo pipe connection error.");Oz(b)});b.b=new mojo.MirrorServiceRemotingSourcePtr;var f=dj(b.m.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+b.m.mediaSource);b.l.info("Connecting remoter to browser: tabId="+f);(Mi.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,
mojo.makeRequest(b.b));b.b.ptr.setConnectionErrorHandler(function(){b.l.info("RemotingSource mojo pipe connection error.");Oz(b)});return Qaa(b).then(function(){if(b.f)b.b.onSinkAvailable(b.N);Fz(d,2)})})};
var Oz=function(a){return Ez(a.j,function(c){a.b&&(a.b.ptr.reset(),a.b=null);var b=a.w;a.w=null;a.h=null;a.F=null;a.D.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.o)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.o);return new Promise(function(d){window.setTimeout(function(){Pz(a).then(function(){Fz(c,1);d();b&&b()})},250)})})};h=Nz.prototype;h.Cr=function(a){Qz(this.g,a)};h.jg=function(a){this.h&&this.h.jg(a)};h.Tg=function(){return this.h?this.h.Tg():Promise.resolve()};
h.Pe=function(a,c){this.l.error("Error during streaming: "+a,c);if(this.b)this.b.onError();Oz(this)};
h.start=function(){var a=this,c=!1;this.l.info(function(){c=!0;return"Starting next media remoting session."});c&&Raa(this.g,function(b){return a.l.info(b)});Saa(this.g);Dz(this.j,2,function(b){return(0,a.F)().then(function(d){a.w=d;a.C.subscribe("RPC",function(e){if(e.rpc){var f=a.g;e=e.rpc;f.w&&(++f.m,f.f+=e.length,f.w(e))}});Fz(b,3)}).catch(function(d){return Pz(a).then(function(){Fz(b);throw d;})})}).then(function(){a.l.info("Remoting started successfully.")}).catch(function(b){a.l.error("Failed to start remoting",
b);a.b.onError()})};h.Ur=function(a,c){var b=this;return Dz(this.j,3,function(d){return b.H.start(a?new Jz:null,c?new Jz:null,b).then(function(e){Taa(b.g,function(f){return b.C.sendMessage(f)},function(f){b.b.onMessageFromSink(f)});Fz(d,4);return{audio_stream_id:e.Jo||-1,video_stream_id:e.es||-1}}).catch(function(e){return Pz(b).then(function(){Fz(d);throw e;})})}).catch(function(d){b.l.error("Failed to start remoting streams",d);Oz(b);return{audio_stream_id:-1,video_stream_id:-1}})};
h.stop=function(a){var c=this;Faa(this.j,function(b){c.b.onStopped(a);return Pz(c).then(function(){c.l.info("Remoting stopped.");Fz(b,5);(0,c.w)().then(function(){return Dz(c.j,5,function(d){if(c.b&&c.f)c.b.onSinkAvailable(c.N);Fz(d,2);return Promise.resolve()})}).catch(function(d){throw d;});c.w=null})}).catch(function(b){c.l.error("Failed to stop remoting: ",b);Oz(c)})};
h.cp=function(){null===this.u&&(this.u=of(this.m.nb.Nf).then(function(a){return a.f||!1}));return this.u.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var Pz=function(a){return a.H.stop().then(function(){zz(a.C,"RPC");Uaa(a.g);Rz(a.g)})},Qaa=function(a){return new Promise(function(c){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(b){chrome.runtime.lastError?a.l.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):b.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.l.error("Pref value not a boolean: "+JSON.stringify(b)):(a.f=!!b.value,a.l.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.f));chrome.settingsPrivate.onPrefsChanged.hasListener(a.o)||chrome.settingsPrivate.onPrefsChanged.addListener(a.o);c()})})};
Nz.prototype.J=function(a){if(this.b){a=l(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,"media_router.media_remoting.enabled"==c.key){if(c.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.l.error("Pref value not a boolean: "+JSON.stringify(c));break}a=!!c.value;if(this.f==a)break;this.f=a;this.l.info("mediaRemotingEnabled_ changed to: "+this.f);if(this.f)this.b.onSinkAvailable(this.N);else this.b.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var Oaa=function(a,c){var b=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=c.Tr||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,g=d.audio_capabilities,k=d.video_capabilities,m=c.Zd||"";(a.b||[]).forEach(function(p){switch(p){case "audio":g.push(e.CODEC_BASELINE_SET);break;case "aac":g.push(e.CODEC_AAC);break;case "opus":g.push(e.CODEC_OPUS);break;case "video":k.push(f.CODEC_BASELINE_SET);break;case "4k":k.push(f.SUPPORT_4K);
break;case "h264":k.push(f.CODEC_H264);break;case "vp8":k.push(f.CODEC_VP8);break;case "vp9":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_VP9);break;case "hevc":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_HEVC);break;default:b.l.info("Unknown mediaCap name: "+p)}});c.Zd&&"Chromecast Ultra"==c.Zd&&k.push(f.SUPPORT_4K);return d};Nz.prototype.estimateTransmissionCapacity=Nz.prototype.cp;Nz.prototype.stop=Nz.prototype.stop;Nz.prototype.startDataStreams=Nz.prototype.Ur;Nz.prototype.start=Nz.prototype.start;
Nz.prototype.sendMessageToSink=Nz.prototype.Cr;
var Paa=function(){this.w=this.j=this.b=null;this.u=this.f=this.m=this.g=this.o=0;this.h=null},Saa=function(a){a.b=[];Sz(a,performance.now())},Taa=function(a,c,b){a.j=c;a.w=b;a.b?(c=a.b,a.b=null,c.forEach(function(d){return Qz(a,d.data).then(d.Er,d.om)})):Sz(a,performance.now())},Uaa=function(a){if(a.b){var c=Error("Stop before delivering pending message");a.b.forEach(function(b){return b.om(c)});a.b=null}a.j=null;a.w=null},Qz=function(a,c){if(a.j){var b=btoa(String.fromCharCode.apply(null,c));++a.o;
a.g+=c.length;return a.j({type:"RPC",rpc:b})}return a.b?new Promise(function(d,e){a.b.push({data:c,Er:d,om:e})}):Promise.reject(Error("RPC pipe not started"))},Raa=function(a,c){Rz(a);a.h=setInterval(function(){if(a.b)var b=a.b.length+" messages are waiting to send.";else{b=performance.now();var d=(b-a.u)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.o+" messages ("+Math.round(a.g/d)+" bytes/sec) and ")+("received "+a.m+" messages ("+Math.round(a.f/d)+" ")+"bytes/sec).";Sz(a,b);b=d}c(b)},
3E4)},Rz=function(a){null!=a.h&&(clearInterval(a.h),a.h=null)},Sz=function(a,c){a.o=0;a.g=0;a.m=0;a.f=0;a.u=c};var Vaa=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},Waa=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var Tz=function(a,c,b,d,e){this.g=new Iz(a,c,b,d,void 0===e?null:e);this.l=hb("mr.mirror.cast.MediaStreamer");this.j=new Bz;this.h=this.f=this.b=this.w=null};Tz.prototype.start=function(a,c){var b=this;return Dz(this.j,1,function(d){b.w=a;b.b=Vaa(a);b.b&&"ended"==b.b.readyState&&(b.b=null);b.f=Waa(a);b.f&&"ended"==b.f.readyState&&(b.f=null);if(!b.b&&!b.f)return Fz(d),Promise.reject(Error("No MediaStream tracks to stream."));b.h=c;return b.g.start(b.b,b.f,b.h).then(function(){return Fz(d,2)})})};
Tz.prototype.stop=function(){var a=this;return Ez(this.j,function(c){return a.g.stop().then(function(){a.b=null;a.f=null;a.w=null;a.h=null;Fz(c,1)})})};var Xaa=function(a){return Dz(a.j,2,function(c){a.l.info("Suspending media streaming...");return a.g.stop().then(function(){a.l.info("Suspended media streaming.");Fz(c,3)})})};
Tz.prototype.resume=function(){var a=this;return Dz(this.j,3,function(c){a.b&&"ended"==a.b.readyState&&(a.b=null);a.f&&"ended"==a.f.readyState&&(a.f=null);if(!a.b&&!a.f)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.l.info("Resuming media streaming...");return a.g.start(a.b,a.f,a.h).then(function(){a.l.info("Resumed media streaming.");Fz(c,2)})})};var Uz=function(a,c,b){this.j=a;this.h=c;this.g=b;this.l=hb("mr.mirror.cast.WifiStatusMonitor");this.b=null;this.f=[]};Uz.prototype.start=function(){var a=this;null==this.b&&(ob(this.l,"Starting Wifi Status Monitoring."),this.f=[],this.g.subscribe("STATUS_RESPONSE",function(c){return Yaa(a,c)}),this.b=setInterval(function(){return Vz(a)},12E4),Vz(this))};Uz.prototype.stop=function(){null!=this.b&&(ob(this.l,"Stopping Wifi Status Monitoring."),clearInterval(this.b),this.b=null,zz(this.g,"STATUS_RESPONSE"))};
var Yaa=function(a,c){if(null!=a.b)if(c.status){var b={};null!=c.status.b&&(b.wifiSnr=c.status.b);null!=c.status.f&&(b.wifiSpeed=c.status.f[3]);0==Object.keys(b).length?a.l.G(function(){return"No status fields populated in response: "+JSON.stringify(c)}):(b.timestamp=Date.now(),30==a.f.length&&a.f.shift(),a.f.push(b),a.l.info(function(){return"Current Wifi status: "+JSON.stringify(b)}))}else a.l.G(function(){return"Ignoring response without status: "+JSON.stringify(c)})},Vz=function(a){a.g.sendMessage({type:"GET_STATUS",
sessionId:a.j,seqNum:mn(a.h),get_status:["wifiSnr","wifiSpeed"]})};var Wz=function(a,c,b,d){this.N=c.Nf;this.m={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:sj(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:c.Zd};this.F=b;this.C=d;this.h=this.f=this.o=this.w=this.j=this.u=this.g=null;this.b=[]};Wz.prototype.jg=function(a){null!=this.f&&clearInterval(this.f);this.g=a;this.u=Date.now();this.f=setInterval(this.D.bind(this,a),9E5)};
Wz.prototype.Tg=function(){null!=this.f&&(clearInterval(this.f),this.f=null);if(null!=this.g){var a=this.D(this.g);this.g=null;return a}return Promise.resolve()};Wz.prototype.Pe=function(a,c){null==this.j&&(this.j=Date.now(),"function"===typeof a?this.w=a():"string"===typeof a&&(this.w=a),c&&"string"===typeof c.stack&&(this.o=c.stack))};
var Zaa=function(a,c){return(null==a.g?Promise.resolve():a.D(a.g)).then(function(){var b=c.map(function(d){d=Xz(a,d);var e=d.map(function(g){return g.events}).filter(function(g){return null!=g}),f=["["];d.map(function(g){return g.Pf}).forEach(function(g,k){0<k&&f.push(",");f.push(g)});f.push("]");return{events:new Blob(e,{type:"application/gzip"}),Pf:new Blob(f,{type:"application/json"})}});a.b=[];return b})};
Wz.prototype.D=function(a){var c=this;if(null!=this.h)return this.h;var b=of(this.N).then(function(d){d={receiverVersion:d.b,receiverConnected:d.h,receiverOnEthernet:d.f,receiverHasUpdatePending:d.g,receiverUptimeSeconds:d.j};Object.assign(d,c.m);var e=Date.now();Object.assign(d,{startTime:c.u,endTime:e,activity:Lz(a),receiverWifiStatus:Array.from(c.C.f)});c.u=e;null!=c.j&&(Object.assign(d,{streamingErrorTime:c.j,streamingErrorMessage:c.w,streamingErrorCause:c.o}),c.j=null,c.w=null,c.o=null);return d});
return(this.h=Promise.all([b.then(function(d){return Laa(a,d)}),b,Maa(a)]).then(function(d){var e=l(d);d=e.next().value;var f=e.next().value;e=e.next().value;c.b.push({events:d,Pf:new Blob([JSON.stringify(Object.assign({tags:f},e))],{type:"application/json"})});c.b=Xz(c,c.F);c.h=null}))||Promise.resolve()};
var Xz=function(a,c){c-=2;for(var b=[],d=a.b.length-1;0<=d;--d){c-=a.b[d].Pf.size+1;if(0>c)break;b.push({events:null,Pf:a.b[d].Pf});if(null!=a.b[d].events){var e=a.b[d].events.size;c>=e&&(b[b.length-1].events=a.b[d].events,c-=e)}}return b.reverse()};var Yz=hb("mr.NetworkUtils"),Zz=function(a,c){return xi?new Promise(function(b,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,c,function(e){chrome.runtime.lastError?(Yz.G("Unable to set TDLS state: state = "+c+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+c+".")):(Yz.info("TDLS state changed: state = "+c+", status = "+e),b(e))})}):Promise.reject("TDLS feature not enabled.")};var $z=function(a,c,b,d){d=void 0===d?null:d;pj.call(this,c);var e=c.nb;this.D=e.sessionId;this.J=e.Nf;this.N=a;this.R=d;this.l=hb("mr.mirror.cast.Session");this.u=new Bz;this.o=new ln("mirror.cast.SeqNumGenerator");this.m=new yz(c.id);this.w=new Tz(e,this.N,this.o,this.m,this.R);this.h=null;this.b=new Wz(a,e,b,new Uz(this.D,this.o,this.m));this.g=!1;this.C=null};q($z,pj);h=$z.prototype;
h.start=function(a){var c=this;return Dz(this.u,1,function(b){var d=new sb("MediaRouter.CastStreaming.Session.Launch");return $aa(c).then(function(e){c.g=e;return c.w.start(a,c)}).then(function(){if(c.w.g.C){var e=c.b;e.m.tdlsIsOn=c.g;e.C.start();aba(c)}else c.b.m.tdlsIsOn=c.g;d.end();c.C=new yb("MediaRouter.CastStreaming.Session.Length");Fz(b,2);return c})})};
h.stop=function(){var a=this;return Ez(this.u,function(c){a.C&&(a.C.end(),a.C=null);a.b.C.stop();return a.w.stop().then(function(){return a.h?Oz(a.h):Promise.resolve()}).then(function(){a.h=null;return a.g?bba(a):Promise.resolve()}).then(function(){a.g=!1;Fz(c,4)})})};h.mm=function(){var a={sessionId:this.D,seqNum:mn(this.o),type:"PRESENTATION",icons:[],title:nj(this.lc)};this.l.info("Sending session metadata update to receiver: "+this.D);this.m.sendMessage(a)};h.jg=function(a){this.b.jg(a)};
h.Tg=function(){return this.b.Tg()};h.Pe=function(a,c){this.b.Pe(a,c);this.l.error(a,c);this.stop()};
var aA=function(a,c){return Zaa(a.b,c)},$aa=function(a){return a.N.useTdls?Zz(a.J,!0).then(function(c){if("Connected"==c)return a.l.info("Successfully enabled TDLS."),!0;a.l.G("Did not enable TDLS: result="+c);return!1}).catch(function(c){a.l.G("Error while calling enableTDLS()",c);return!1}):Promise.resolve(!1)},bba=function(a){return Zz(a.J,!1).catch(function(c){return a.l.error("Error while turning TDLS back off",c)})},aba=function(a){cba(a).then(function(c){(c.b||[]).includes("video")?dba(a,c):
a.l.G(function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(c)})}).catch(function(c){a.l.G("None/Invalid capabilites response. Media Remoting disabled.",c)})},cba=function(a){return new Promise(function(c,b){var d={type:"GET_CAPABILITIES",sessionId:a.D,seqNum:mn(a.o)};a.l.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Az(a.m,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return b(f),!0;if("ok"!=e.result||!e.capabilities)return b(Error("Bad response: "+
JSON.stringify(e))),!0;if(e.f!=d.seqNum)return a.l.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;ob(a.l,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});c(e.capabilities);return!0})})},dba=function(a,c){Dz(a.u,2,function(b){var d=a.f.nb.Zd||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.l.G("HACK: Media Remoting disabled because the receiver model--"+('"'+d+'" according to discovery--is not a Chromecast.')),
Fz(b),Promise.resolve();a.h=new Nz(a.f,c,a.N,a.o,a.m,a.R);return a.h.initialize(a.T.bind(a),a).catch(function(e){a.l.error("Media Remoting start failed: "+e.message,e)}).then(function(){return Fz(b)})})};$z.prototype.T=function(){var a=this;return Dz(this.u,2,function(c){return new Promise(function(b,d){Xaa(a.w).then(function(){Fz(c,3);a.F=!0;gj(a);b(a.V.bind(a))}).catch(function(e){a.Pe("Failed to suspend MediaStreamer before starting remoting",e);d(e)})})})};
$z.prototype.V=function(){var a=this;return Dz(this.u,3,function(c){return new Promise(function(b,d){a.w.resume().then(function(){Fz(c,2);a.F=!1;gj(a);b()}).catch(function(e){a.Pe("Failed resume MediaStreamer after ending remoting mode",e);d(e)})})})};var bA=function(){ej.call(this,"cast_streaming");this.j=this.u=this.N=this.F=this.h=null;this.J=this.H="";this.R=this.o=!1;this.V=this.dc.bind(this);this.m=null};q(bA,ej);h=bA.prototype;h.lg=function(a){this.o=a||!1;this.R=!0};h.getName=function(){return"cast_streaming"};
h.cj=function(a,c,b,d,e){var f=this;if(!this.o)return ej.prototype.cj.call(this,a,c,b,d,e);this.O.info("Start mirroring on route "+a.id);if(!this.R)return pi(Error("Not initialized"));var g=new Promise(function(k,m){f.w().then(function(){if($i(c)&&b.shouldCaptureVideo)return(new Promise(function(p){chrome.tabs.get(a.nb.tabId||-1,p)})).then(function(p){return Ji(p).then(function(v){f.J=v})})}).then(function(){return e?e(a).b:a}).then(function(p){f.F=new mojo.Binding(mojo.MirroringSessionObserver,f,
null);f.N=new mojo.Binding(mojo.MirroringCastMessageChannel,f,null);f.j=Ay(p.id);f.j.onMessage=f.nq.bind(f);var v=f.F.createInterfacePtrAndBind(),A=f.N.createInterfacePtrAndBind(),H=eba(p,b);f.h=new mojo.MirroringServiceHostPtr;var E=p.nb.tabId||-1;Zi(c)?f.g.getMirroringServiceHostForTab(E,mojo.makeRequest(f.h)):$i(c)?f.g.getMirroringServiceHostForDesktop(E,f.J,mojo.makeRequest(f.h)):bj(c)?(E=new mojo.Url,E.url=c,f.g.getMirroringServiceHostForOffscreenTab(E,d||"",mojo.makeRequest(f.h))):f.h=null;
if(!f.h)throw new ti("Error to get mirroring service host");f.u=new mojo.MirroringCastMessageChannelPtr;f.h.start(H,v,A,mojo.makeRequest(f.u));f.m=new pj(a,f.g.Ci.bind(f.g));Zi(c)&&!chrome.tabs.onUpdated.hasListener(f.V)&&chrome.tabs.onUpdated.addListener(f.V);(Zi(c)||bj(c))&&jj(f.m,p.nb.tabId);k(p)}).catch(function(p){f.O.info("Mirroring launch error: "+p);m(p)})});return qi(g)};h.kh=function(a,c){return new $z(a,c,20969472,null)};h.Ng=function(){mz(0)};h.Kg=function(){mz(1)};h.Lh=function(){mz(2)};
h.Lg=function(){Bb("MediaRouter.CastStreaming.Session.End")};h.Kh=function(a){Cb("MediaRouter.CastStreaming.Start.Failure",a,si)};h.Mg=function(){Bb("MediaRouter.CastStreaming.Stream.End")};
h.hi=function(a){var c=this;return this.o?Promise.resolve():(new Promise(function(b){return chrome.metricsPrivate.getIsCrashReportingEnabled(b)})).then(function(b){var d=b&&raa(),e=[9351424];d&&e.push(20969472);return aA(a,e).then(function(f){var g=f[f.length-1];f=gm(f[0].events).catch(function(k){c.O.error("Failed to persist events Blob.",k)});d&&0<g.events.size?pz(g.events,void 0,c.mq.bind(c)):b&&oz("stats.json",g.Pf,void 0,void 0);return f})})};h.mq=function(a){a&&(sz().b=Date.now())};
h.bj=function(a){if(this.o)return eb();this.O.info("Received message to upload logs for "+a);return this.b?aA(this.b,[20969472]).then(function(c){c=l(c).next().value;return 0==c.events.size?"":pz(c.events,a)}):Promise.resolve(fba(this,a))};
var fba=function(a,c){var b=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==b||1>b.length)b=null;else{for(var d=new Uint16Array(b.length),e=0;e<b.length;++e)d[e]=b.charCodeAt(e);b=d.buffer;d=(new Uint8Array(b,b.byteLength-1,1))[0];b=new Uint8Array(b,0,b.byteLength-(0==d?2:1));b=new Blob([b],{type:"application/gzip"})}if(null!=b&&0!=b.size)return gm(new Blob),a.O.info("Uploading saved logs for feedback."),pz(b,c)};h=bA.prototype;
h.onError=function(a){this.O.info("Mirroring service error: "+a);this.w()};h.didStart=function(){Zi(this.H)?this.Ng():$i(this.H)?this.Kg():bj(this.H)&&this.Lh()};h.didStop=function(){this.w()};h.send=function(a){if(this.j){var c=JSON.parse(a.jsonFormatData);ob(this.O,function(){return"Sending message: "+JSON.stringify(c)});this.j.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
h.nq=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.u){var c=new mojo.MirroringCastMessage;c.messageNamespace=a.namespace_;"string"!==typeof a.data?this.O.info("Received non-string as JSON"):(c.jsonFormatData=a.data,this.u.send(c))}};
var eba=function(a,c){var b=new mojo.MirroringSessionParameters;b.receiverAddress=new mojo.IPAddress;b.receiverAddress.addressBytes=a.nb.Nf.split(".").map(function(d){return parseInt(d,10)});b.receiverModelName=a.nb.Zd;b.type=c.shouldCaptureVideo&&c.shouldCaptureAudio?mojo.MirroringSessionType.AUDIO_AND_VIDEO:c.shouldCaptureVideo?mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY;return b};bA.prototype.dc=function(a,c,b){Yi(14);this.m&&kj(this.m,a,c,b)};
bA.prototype.w=function(){chrome.tabs.onUpdated.removeListener(this.V);return this.o?this.R?this.h?(this.h.ptr.reset(),this.u=this.h=null,this.j&&this.j.Ya(),this.j=null,this.F&&(this.F.close(),this.F=null),this.N&&(this.N.close(),this.N=null),this.g.Hh(this.m.f.id),this.m=null,this.J=this.H="",this.Lg(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):ej.prototype.w.call(this)};
bA.prototype.dj=function(a,c,b,d,e,f){return this.o?pi(Error("Mirroring service does not support updating stream")):ej.prototype.dj.call(this,a,c,b,d,e,f)};bA.prototype.send=bA.prototype.send;bA.prototype.didStop=bA.prototype.didStop;bA.prototype.didStart=bA.prototype.didStart;bA.prototype.onError=bA.prototype.onError;var gba=new bA;Vi("mr.mirror.cast.Service",gba);
