/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class GameFieldSceneUI extends Scene {
		public UISet:Laya.Sprite;
		public T1_1:Laya.Sprite;
		public T2_2:Laya.Sprite;
		public T3_1:Laya.Sprite;
		public T2_1:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("GameFieldScene");
        }
    }
    REG("ui.GameFieldSceneUI",GameFieldSceneUI);
    export class LoadingSceneUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("LoadingScene");
        }
    }
    REG("ui.LoadingSceneUI",LoadingSceneUI);
}