/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameField from "./SceneScript/GameField"
import Loading from "./SceneScript/Loading"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1400;
    static height:number=900;
    static scaleMode:string="noscale";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="LoadingScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("SceneScript/GameField.ts",GameField);
        reg("SceneScript/Loading.ts",Loading);
    }
}
GameConfig.init();